CategoriesWebApp/Controllers/CategoriesController.cs
using CategoriesWebApp.Models.ViewModels;
using CategoriesWebApp.Repositories.Interfaces;
using CategoriesWebApp.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CategoriesWebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {

        private readonly ICategoryRepository _categoryRepository;
        private readonly ICategoryService _categoryService;
        private readonly RoleManager<IdentityRole> _roleManager;

        public CategoriesController(ICategoryRepository categoryRepository, RoleManager<IdentityRole> roleManager, ICategoryService categoryService)
        {
            _categoryRepository = categoryRepository;
            _roleManager = roleManager;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var categories = await _categoryRepository.Get();
            return View(categories);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var category = new CreateCategoryViewModel();
            var roles = await _roleManager.Roles.ToListAsync();
            category.Roles = roles
                .Select(r => new SelectListItem(r.Name, r.Id))
                .ToList();

            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCategoryViewModel model)
        {


            if (!ModelState.IsValid)
            {
                var roles = await _roleManager.Roles.ToListAsync();
                model.Roles = roles
                    .Select(r => new SelectListItem(r.Name, r.Id))
                    .ToList();
                return View(model);
            }



            await _categoryService.Create(model);

            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> CreateSubCategory(int index)
        {
            var category = new CreateCategoryViewModel();
            var roles = await _roleManager.Roles.ToListAsync();
            category.Index = index;
            category.Roles = roles
                .Select(r => new SelectListItem(r.Name, r.Id))
                .ToList();
            return PartialView("_CreateSubCategory", category);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var category = await _categoryRepository.GetById(id);

            var model = new CreateCategoryViewModel
            {
                Name = category.Name,
                Controller = category.Controller,
                Action = category.Action,
                RoleSelected = category.Role.Id,
                SubCategories = new List<SubCategoryViewModel>()

            };

            foreach (var subCategory in category.SubCategories)
            {
                var subCategoryViewModel = new SubCategoryViewModel()
                {
                    Id = subCategory.Id,
                    Name = subCategory.Name,
                    Action = subCategory.Action,
                    Category = model,
                    RoleSelected = subCategory.RoleId
                };
                model.SubCategories.Add(subCategoryViewModel);
            }

            var roles = await _roleManager.Roles.ToListAsync();
            model.Roles = roles
                .Select(r => new SelectListItem(r.Name, r.Id))
                .ToList();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CreateCategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {

                var errors = ModelState.Select(x => x.Value.Errors)
                    .Where(y => y.Count > 0)
                    .ToList();


                var roles = await _roleManager.Roles.ToListAsync();
                model.Roles = roles
                    .Select(r => new SelectListItem(r.Name, r.Id))
                    .ToList();
                return View(model);
            }
            await _categoryService.Edit(model);

            return RedirectToAction("Index");

        }





        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {

            await _categoryService.Delete(id);

            return Json(true);

        }


    }
}

CategoriesWebApp/ViewComponents/SideViewComponent.cs
using CategoriesWebApp.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CategoriesWebApp.ViewComponents
{
    public class SideViewComponent : ViewComponent
    {
        private readonly ICategoryRepository _categoryRepository;

        public SideViewComponent(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryRepository.Get();

            return View(categories);
        }
    }
}

CategoriesWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CategoriesWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CategoriesWebApp</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartialCustom" />
                        <ul class="navbar-nav flex-grow-1">
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                                </li>
                            }

                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@
    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
            <div class="p-4 pt-5">
                @*<a href="#" class="img logo rounded-circle mb-5" style="background-image: url(images/logo.jpg);"></a>*@
                @await Component.InvokeAsync("Side")


            </div>
        </nav>

        <!-- Page Content  -->
        <div id="content" class="p-4 p-md-5">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-primary">
                        <i class="fa fa-bars"></i>
                        <span class="sr-only">Toggle Menu</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fa fa-bars"></i>
                    </button>
                    <div class="float-left">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                            </li>
                            &nbsp;
                            @if (User.IsInRole("Admin"))
                            {

                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Index", "Users")">Users</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Index", "Categories")">Categories</a>
                                </li>
                            }



                        </ul>
                    </div>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <partial name="_LoginPartialCustom" />
                    </div>
                </div>
            </nav>

            @RenderBody()
        </div>
    </div>
    @*<div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>*@

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - CategoriesWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CategoriesWebApp/Views/Shared/_LoginPartialCustom.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="nav navbar-nav ml-auto">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link" href="#">Hello, @UserManager.GetUserName(User)</a>
        </li>
        <li class="nav-item">
            <form id="logoutForm" method="post" class="form-inline" asp-controller="Account" asp-action="LogOff">
                <button type="submit" class="btn nav-link">Logout</button>
            </form>

        </li>
    }

</ul>